spring.application.name=SeatSphereBackend

# Server port
server.port=8080

# Database connection - CHANGED UTC TO CDT/America/Chicago
spring.datasource.url=jdbc:mysql://localhost:3307/seatsphere_db?useSSL=false&serverTimezone=America/Chicago
spring.datasource.username=root
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ADD THIS: This tells the JSON creator to use your time zone
spring.jackson.time-zone=America/Chicago